### PR TITLE
LOOP-2955 Allow onboarding to utilize other plugins

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-2955
- Create initial LoopSupport project and targets
- Move support from NightscoutService plugin/repo

Note: Needs TWO reviewers.

### CODE REVIEW

**Comment by darinkrauss** [comment]
Repository is now public.

**Review by nhamming — APPROVED** [review]
LGTM

**Review by rickpasetto — APPROVED** [review]
LGTM 🧷 

(Some day it would be nice to pull our common shell scripts into a common repo, but that's for another day...)

**Review by ps2 — APPROVED** [review]
LGTM!

**Pull request merged**
